// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false, 
  clients : "clients",
  register : "register",
  baseUrl : "http://localhost:8080",
  getAll : "getAll",
  cottages : "cottages",
  boats : "boats",
  fishingInstructors : "fishingInstructors",
  fishingInstructorClasses : "fishingInstructorClasses",
  getById : "getById",
  search : "search",
  auth : "auth",
  login : "login",
  update : "update",
  changePassword : "change-password",
  quickReservations : "quickReservations",
  getBoatReservationsByClient : "getBoatReservationsByClient",
  getCottageReservationsByClient : "getCottageReservationsByClient",
  getFishingInstructorClassReservationsByClient : "getFishingInstructorClassReservationsByClient",
  getFutureBoatReservationsByClient : "getFutureBoatReservationsByClient", 
  getFutureCottageReservationsByClient : "getFutureCottageReservationsByClient", 
  getFutureFishingInstructorClassReservationsByClient : "getFutureFishingInstructorClassReservationsByClient", 
  cancelReservation : "cancelReservation",
  rentingItems : "rentingItems",
  subscriptions : "subscriptions",
  getByClient : "getByClient",
  delete : "delete",
  add : "add",
  complaints : "complaints",
  complaintReply : "complaintReply",
  addReply : "addReply",
  deleteAccountRequests : "deleteAccountRequests",
  quickReservationPenalties : "quickReservationPenalties",
  activateProfile : "activateProfile",
  rentingItemAvailabilities:"rentingItemAvailabilities",
  searchByParameters : "searchByParameters",
  additionalServices :"additionalServices",
  getAllByRentingItem:"getAllByRentingItem",
  reservations:"reservations",
  create : "create",
  actions : "actions",
  getPreviousReservationsByClient : "getPreviousReservationsByClient",
  getFutureReservationsByClient : "getFutureReservationsByClient",
  reservationPenalties : "reservationPenalties",
  revisions : "revisions",
  approveRevision : "approveRevision",
  denyRevision : "denyRevision",
  getAllUnapprovedRevisions : "getAllUnapprovedRevisions"

};
